### ISSUE TITLE
vegamag column in observed fits table is not correct

### ISSUE THREAD

**Issue by benw1** [spacetelescope/STScI-STIPS#122]
In the latest version of STIPS (master branch pulled Dec. 3 2020), the fits table of observed sources has vegamags that are way off.  In my latest run, the vegamags are mostly *negative* while the stmags have proper values in the twenties.  Something is wrong with the conversion to vegamags...

**Comment by benw1** [comment]
There may be a problem with the pandeia zeropoint code.  I get this error when using the test module:
>>> observation = test_wfirst.get_default_obs()
>>> obm = ObservationModule(observation)
2020-12-04 10:43:36,743 INFO: Got offsets as [{'offset_id': 1, 'offset_centre': False, 'offset_ra': 0.5, 'offset_dec': 0.0, 'offset_pa': 27.0}]
2020-12-04 10:43:36,936 INFO: Adding observation with filter F158 and offset (0.5,0.0,27.0)
2020-12-04 10:43:36,936 INFO: Added 1 observations
2020-12-04 10:43:37,524 INFO: WFI with 1 detectors. Central offset (0.0, 0.0, 0.0)
>>> print(observation['filters'])
['F158']
>>> print(observation['filters'], obm.instrument.zeropoint)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nobackup/bwilli24/miniconda3/envs/stips/lib/python3.7/site-packages/stips-1.0.8-py3.7.egg/stips/instruments/instrument.py", line 962, in zeropoint
    bp = self.bandpass
  File "/nobackup/bwilli24/miniconda3/envs/stips/lib/python3.7/site-packages/stips-1.0.8-py3.7.egg/stips/instruments/instrument.py", line 900, in bandpass
    i = self.pandeia_instrument
  File "/nobackup/bwilli24/miniconda3/envs/stips/lib/python3.7/site-packages/stips-1.0.8-py3.7.egg/stips/instruments/instrument.py", line 951, in pandeia_instrument
    conf['instrument']['filter'] = self.filter.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
>>>

**Comment by york-stsci** [comment]
Please provide your STIPS environment.

**Comment by benw1** [comment]
Thanks for the response!  Here are my stops-related environment variables:

stips_data=/nobackup/bwilli24/STScI-STIPS/stips_data
PYSYN_CDBS=/nobackup/bwilli24/STScI-STIPS/stips_data/grp/hst/cdbs
WEBBPSF_PATH=/nobackup/bwilli24/miniconda3/envs/stips/share/webbpsf-data
pandeia_refdata=/nobackup/bwilli24/STScI-STIPS/stips_data/pandeia_data-1.5_wfirst

**Comment by benw1** [comment]
I made some progress.  I had left out the obm.nextObservation(). When I do that, I get a zeropoint, but it is way off.  It should be something like  -25.21869, but instead it is -1.306...

>>> observation = test_wfirst.get_default_obs()
>>> obm = ObservationModule(observation)
2020-12-07 15:37:55,847 INFO: Got offsets as [{'offset_id': 1, 'offset_centre': False, 'offset_ra': 0.5, 'offset_dec': 0.0, 'offset_pa': 27.0}]
2020-12-07 15:37:56,071 INFO: Adding observation with filter F158 and offset (0.5,0.0,27.0)
2020-12-07 15:37:56,071 INFO: Added 1 observations
2020-12-07 15:37:56,501 INFO: WFI with 1 detectors. Central offset (0.0, 0.0, 0.0)
>>> obm.nextObservation()
>>> print(observation['filters'], obm.instrument.zeropoint)
['F158'] 1.3062844822188007

**Comment by york-stsci** [comment]
Sorry, what I meant with respect to the environment was whether you could do the following from python:

`import stips`
`print stips.__stips__environment__dict__`

and then post the results here. In particular, what I think you may be running into is that post-1.0.7 versions of STIPS (all future releases, and definitely any clone you would have made by December) are only compatible with Pandeia version 1.5.2 (and newer), and use synphot/stsynphot rather than pysynphot (because pandeia itself migrated to using those tools).

**Comment by benw1** [comment]
Thanks!  I installed all of the data in the links on readthedocs. Are those up to date?  I get an error when I try to get that dictionary....
>>> print(stips.__stips__environment__dict__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'stips' has no attribute '__stips__environment__dict__'

**Comment by york-stsci** [comment]
So, just to check, did you have double-underscores both before and after stips__environment__dict? It's a bit hard to tell from the above.

**Comment by york-stsci** [comment]
Meanwhile, I think that the readthedocs links might actually be out of date, unfortunately, so I'll link below.

The current STIPS data link on box is <https://stsci.box.com/v/stips-data-1-0-9-tgz>, the pandeia reference data (including Roman) for 1.5.2 is <https://stsci.box.com/shared/static/7voehzi5krrpml5wgyg8bo954ew7arh2.gz>, the webbpsf 0.9.0 reference data is <https://stsci.box.com/shared/static/qcptcokkbx7fgi3c00w2732yezkxzb99.gz>, and the CRDS reference data that you need to download for the current STIPS are <https://ssb.stsci.edu/trds/tarfiles/synphot1.tar.gz>, <https://ssb.stsci.edu/trds/tarfiles/synphot2.tar.gz>, <https://ssb.stsci.edu/trds/tarfiles/synphot5.tar.gz>, and <https://ssb.stsci.edu/trds/tarfiles/synphot6.tar.gz>.

**Comment by benw1** [comment]
Yes. Sorry, the original copy didn't come through well.  Here's another.  I'll try updating my data to the links above as well.
>>> print(stips.__stips__environment__dict__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'stips' has no attribute '__stips__environment__dict__'

**Comment by benw1** [comment]
That stips data file does not unpack...
(stips) MacBook-Pro-9:STScI-STIPS ben$ tar tvfz stips-data-1-0-9-tgz 
tar: Error opening archive: Unrecognized archive format

**Comment by york-stsci** [comment]
Sorry, try this: https://stsci.box.com/s/4nebx2ndxr7c77lgocfbvxo7c2hyd3in

**Comment by benw1** [comment]
That link also yields a very small file that does not unpack.  The others have all unpacked fine...

**Comment by york-stsci** [comment]
Box is not being helpful right now. Try this link:

https://stsci.box.com/s/4nebx2ndxr7c77lgocfbvxo7c2hyd3in.tgz

**Comment by york-stsci** [comment]
The other link was to the box page. It should work fine if opened in a web browser but wouldn't work if downloaded directly.

**Comment by benw1** [comment]
Ah. That link doesn't work either with wget, but the original link works with a browser.  I got the file, but it would be best to put it someplace accessible to wget.  Testing now...

**Comment by benw1** [comment]
Still getting unreasonable zeropoint:
>>> print(observation['filters'], obm.instrument.zeropoint)
['F158'] 1.2895881768483086
>>>

**Comment by benw1** [comment]
Also, still not environment dictionary:
`>>> import stips
>>> print(stips.__stips__environment__dict__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'stips' has no attribute '__stips__environment__dict__'
>>> 
`

**Comment by benw1** [comment]
I should note my version is 1.0.8
>>> print(stips.__version__)
1.0.8
>>> 
I'm not sure if that is an issue. I'm up to date on the master branch:
(stips) MacBook-Pro-9:STScI-STIPS ben$ git status
On branch master
Your branch is up to date with 'origin/master'.

**Comment by york-stsci** [comment]
Okay, it looks like there might be an issue with your version (although there's also a problem with what I've been telling you). In my case, I've just cloned a new copy of STIPS and created a conda environment for it, and I get:

`import stips`
`print(stips.__version__)`

`dev`

Further, when I do:

`for item in stips.__env__dict__:`
`    print(item, stips.__env__dict__[item])`

I get:

stips_version dev
stips_data_location /Users/Shared/data/stips_data-1.0.9
stips_data_version 1.0.9
stips_grid_version 1.0.8
pandeia_version 1.5.2
pandeia_data_location /Users/Shared/data/pandeia_data-1.5.2rc2_roman
pandeia_data_version 1.5.2
webbpsf_version 0.9.0
webbpsf_data_location /Users/Shared/anaconda3/envs/stips/share/webbpsf-data
webbpsf_data_version 0.9.0
astropy_version 4.2
photutils_version 1.0.1

Note that it's actually `stips.__env__dict__` not `__stips__environment__dict__`, so oops on my part.

**Comment by york-stsci** [comment]
Also, based on the other issue you raised (unable to find Vega), I think that's actually your problem -- you need to download the synphot data files I specified above, and set PYSYN_CDBS to point to them (and if they extract as grp/hst/cdbs/... you need to set the environment variable to point to the cabs directory within that hierarchy). STIPS uses the spectrum of vega to calculate its zero point, and if you don't have that spectrum you won't get a useful zero point.

**Comment by benw1** [comment]
Here is the environment.  Should I change branches to get the dev version?
>>> print(stips.__env__dict__)
{'stips_version': '1.0.8', 'stips_data_location': '/Users/ben/src/STScI-STIPS/stips_data', 'stips_data_version': '1.0.9', 'stips_grid_version': '1.0.8', 'pandeia_version': '1.5.2', 'pandeia_data_location': '/Users/ben/src/STScI-STIPS/pandeia_data-1.5.2rc2_roman', 'pandeia_data_version': '1.5.2', 'webbpsf_version': '0.9.0', 'webbpsf_data_location': '/Users/ben/miniconda3/envs/STIPS/share/webbpsf-data', 'webbpsf_data_version': '0.9.0', 'astropy_version': '4.2', 'photutils_version': '0.7.2'}
>>>

**Comment by york-stsci** [comment]
You should not change branches. I'm on the master branch of the main repository.

`(stips) york@winterrose STScI-STIPS % git remote -v`
`origin	https://github.com/spacetelescope/STScI-STIPS.git (fetch)`
`origin	https://github.com/spacetelescope/STScI-STIPS.git (push)`
`(stips) york@winterrose STScI-STIPS % git status`
`On branch master`
`Your branch is up to date with 'origin/master'.`

`nothing to commit, working tree clean`

**Comment by benw1** [comment]
(stips) MacBook-Pro-9:STScI-STIPS ben$ git remote -v
origin	https://github.com/spacetelescope/STScI-STIPS.git (fetch)
origin	https://github.com/spacetelescope/STScI-STIPS.git (push)
(stips) MacBook-Pro-9:STScI-STIPS ben$ git status
On branch master
Your branch is up to date with 'origin/master'.

**Comment by benw1** [comment]
Somehow our versions are synced, but the compiled version is different. I don't understand that.

**Comment by york-stsci** [comment]
Please try making a fresh clone, and see what that gives you.

**Comment by benw1** [comment]
I recloned, and did a python setup.py install, and the end of the installation says:
Adding numpy 1.19.4 to easy-install.pth file
Installing f2py script to /Users/ben/miniconda3/envs/stips/bin
Installing f2py3 script to /Users/ben/miniconda3/envs/stips/bin
Installing f2py3.7 script to /Users/ben/miniconda3/envs/stips/bin

Using /Users/ben/miniconda3/envs/stips/lib/python3.7/site-packages
Finished processing dependencies for stips==1.0.8

**Comment by benw1** [comment]
Looks like it is still 1.0.8

**Comment by york-stsci** [comment]
Okay, I think I see the difference. I was running out of the STIPS directory, but had not installed stips (so it was just picking it up locally). If I install before importing, mine is also reported as 1.0.8. So, have you installed the synphot reference files, are you still getting the error about not being able to find Vega, and are you still getting the same zero point issues?

**Comment by benw1** [comment]
The new files fixed the vega issue, but the zero point issues remain. For the get_default_obs() observation, I get:
```
>>> print(observation['filters'], obm.instrument.zeropoint)
['F158'] 1.2895881768483086
>>> 

```

**Comment by benw1** [comment]
What do you get for the zeropoint for the test_wfirst.get_default_obs()?

**Comment by york-stsci** [comment]
So, I've figured out the issue. When I moved over to synphot, and needed to use units, I wasn't using the correct units for calculating the zero point. I've now fixed that, and if you download STIPS now it should produce a correct zero point.

**Comment by benw1** [comment]
Yes!  it now produces the correct zero point.  Will test the output catalogs next. Thanks!
