### ISSUE TITLE
Paths incorrectly set during installation?

### ISSUE THREAD

**Issue by ytsapras** [spacetelescope/STScI-STIPS#131]
Following through the installation instructions, I downloaded the Synphot and STSynphot reference data:

> # Synphot and STSynphot reference data
> wget -qO- https://ssb.stsci.edu/trds/tarfiles/synphot1.tar.gz | tar xvz
> wget -qO- https://ssb.stsci.edu/trds/tarfiles/synphot2.tar.gz | tar xvz
> wget -qO- https://ssb.stsci.edu/trds/tarfiles/synphot5.tar.gz | tar xvz
> wget -qO- https://ssb.stsci.edu/trds/tarfiles/synphot6.tar.gz | tar xvz

I then did the required exports from the shell (replacing the paths in <> with the correct full path to the data dir and the x.x.x with the corresponding version):

> export WEBBPSF_PATH=/<path_to_data_dir>/webbpsf-data
> export PYSYN_CDBS=/<path_to_data_dir>**/grp/hst/cdbs**
> export pandeia_refdata=/<path_to_data_dir>/pandeia_data-x.x.x_roman

When attempting to import stips in python, it complained that it can't find the data file:

> Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37)
> [GCC 9.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import stips
> WARNING: Failed to load Vega spectrum from /STIPS_DATA/grp/hst/cdbs/calspec/alpha_lyr_stis_010.fits; Functionality involving Vega will be cripped: FileNotFoundError(2, 'No such file or directory') [stsynphot.spectrum]
> **WARNING**: LOCAL JWST PRD VERSION PRDOPSSOC-034 DOESN'T MATCH THE CURRENT ONLINE VERSION PRDOPSSOC-036
> Please consider updating pysiaf, e.g. pip install --upgrade pysiaf or conda update pysiaf

Looking at the untarred paths, there is **no /grp/hst/cdbs directory**. Instead, the fits file that the code expects is under /grp/redcat/trds/calspec/

so perhaps the correct path export command should be:

> export PYSYN_CDBS="<path_to_data_dir>**/grp/redcat/trds"

which seems to do the trick (though the pysiaf warning persists).

**Comment by york-stsci** [comment]
Thank you. It appears that the team changed the paths in the archives without changing the download URLs, so the documentation is now out of date. Because STIPS does not directly use pysiaf itself, it is a bit more difficult to control which version is downloaded and used.
