### ISSUE TITLE
Point sources are smeared in bluer bands in oversample=1 images

### ISSUE THREAD

**Issue by benw1** [spacetelescope/STScI-STIPS#141]
We are finding significant differences between the model PSFs in the PSF files and the point sources in the resulting images.
For oversample=1,  we assume the simulated image uses a single evaluation of the PSF, located at the center of each pixel.  If so, there are errors in the bluer bands:
* The F062 model PSF shows a central brightness of about 0.41, and average of 0.07 at +/- 1 pixel in X or Y, for a ratio of ~6:1 peak to adjacent pixels.  The simulated image with oversample=1 nearest chip center shows a central pixel brightness of 53000 counts above background, while the four adjacent pixels have an average brightness of 21000 counts above background, for a ratio of ~2.5:1.  More significantly, the point sources are visibly extended from lower left (lower X and lower Y) to upper right.  So, there seems to be some sort of error in the generation of the oversample=1 in the form of a diagonal smear, which is also notable in the F087 and F106 filters.
* The F184 PSF shows a central brightness of about 0.21, and average of 0.06 at +/- 1 pixel in X or Y, for a ratio of ~2.5:1 peak to adjacent pixels.  The simulated image with oversample=1 nearest chip center shows a central pixel brightness of 8000 counts above background, while the four adjacent pixels have an average brightness of 3000 counts above background, for a ratio of ~2.7:1.  Not only does this approximate metric match the expectation, but one also sees indication of the diffraction ring, in the form of a darker region just outside the central peak and slightly more light further out.  In short, this image looks correct for oversample=1 images in this filter.  F158 and F129 also do not show any obvious issue, but the improved similarity in the redder bands may be due to the broader PSF hiding the problem.

**Comment by york-stsci** [comment]
Is this still present in the current version 2 development branch?
