### ISSUE TITLE
Image dimensions for Roman/WFI

### ISSUE THREAD

**Issue by Russell-Ryan** [spacetelescope/STScI-STIPS#147]
The generated images are 4096x4096, but level 2 Roman images will be 4088x4088.

**Comment by york-stsci** [comment]
How do those values map to the 4096x4096 image that webbpsf uses for specifying PSF position?

**Comment by Russell-Ryan** [comment]
The detector is a physical array of 4096x4096 pixels, but the outermost 4 pix along each side are not exposed to the sky (but are only for internal calibrations).  These pixels are removed in Level 2 images.

**Comment by york-stsci** [comment]
Would it be an appropriate solution if STIPS, at the very end of its calculation, trimmed off the image border before saving to a FITS file?

**Comment by Russell-Ryan** [comment]
I think so, but you might need to be careful in propagating the WCS and so on.  In particular, the CRPIX may need to be altered and so on.  Just out of curiosity, is it possible to change the default configuration?  I'm just not sure the best way exactly.

**Comment by york-stsci** [comment]
Probably? The default configuration of what, exactly?
