### ISSUE TITLE
ReadTheDocs will require an update.

### ISSUE THREAD

**Issue by york-stsci** [spacetelescope/STScI-STIPS#171]
Below is the text of an e-mail I received from ReadTheDocs. So, first point I guess, STIPS should probably choose another person to be the contact point for the account. Second, there is some action that will be needed:

> Previously, manually configured webhooks from integrations did not have a secret attached to them. In order to improve security, we have deployed an update so that all new integrations will be created with a secret, and we are deprecating old integrations without a secret. You must migrate your integration by January 31, 2024, when they will stop working without a secret.
> 
> We are contacting you because you have at least one integration that does not have a secret set. These integrations are:
> 
> [https://readthedocs.org/dashboard/stips/integrations/208771/](https://urldefense.com/v3/__https://readthedocs.org/dashboard/stips/integrations/208771/__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!xKK6R0911R1aIAeF0BHAb9zLfNJhU5dGHxxEvA8-Eo1VANkL0azFcH85LBHpBjMHFPfJa0-i7hTYIG3mdA$)
> If you aren't using an integration, you can delete it. Otherwise, we recommend clicking on "Resync webhook" to generate a new secret, and then update the secret in your provider's settings as well. You can check [our documentation](https://urldefense.com/v3/__https://docs.readthedocs.io/en/stable/guides/setup/git-repo-manual.html__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!xKK6R0911R1aIAeF0BHAb9zLfNJhU5dGHxxEvA8-Eo1VANkL0azFcH85LBHpBjMHFPfJa0-i7hSWgRmpcg$) for more information on how to do this.
> 
> You can read more information about this in our blog post: [https://blog.readthedocs.com/security-update-on-incoming-webhooks/](https://urldefense.com/v3/__https://blog.readthedocs.com/security-update-on-incoming-webhooks/__;!!CrWY41Z8OgsX0i-WU-0LuAcUu2o!xKK6R0911R1aIAeF0BHAb9zLfNJhU5dGHxxEvA8-Eo1VANkL0azFcH85LBHpBjMHFPfJa0-i7hR2snLWpQ$).

**Comment by ojustino** [comment]
Hi @york-stsci, I got the email, too, but thanks for making us aware. It looks like @gmzsebastian was able to add one, so either of you can feel free to mark this issue as resolved.

**Comment by gmzsebastian** [comment]
We've updated the email contact for ReadTheDocs and updated the webpage, closing.
