### ISSUE TITLE
Output photometry lists have column-width jumps

### ISSUE THREAD

**Issue by benw1** [spacetelescope/STScI-STIPS#20]
In the output photometry lists, the column widths change abruptly.  This causes astropy to fail on reading the file.  It looks like this:

  2517.6913324 1064.34991998 point           inf           inf          0.0 99986.0 comment 
 1804.05356529  1064.3825735 point           inf           inf          0.0 99987.0 comment 
 2376.24982102 1064.37279608 point           inf           inf          0.0 99988.0 comment 
 1720.47366272 1064.37289225 point           inf           inf          0.0 99989.0 comment 
 3064.16935295   1064.185337 point           inf           inf          0.0 99990.0 comment 
 2254.09638279 1064.38602616 point           inf           inf          0.0 99991.0 comment 
 1489.02462552 1064.33130414 point           inf           inf          0.0 99992.0 comment 
 1579.03215135 1064.35005763 point           inf           inf          0.0 99993.0 comment 
  1315.43718858  1064.28586191  point           inf           inf               0.0  99994                                                    comment 
  1746.19195883  1064.37617288  point           inf           inf               0.0  99995                                                    comment 
  1437.59063619  1064.31911307  point           inf           inf               0.0  99996                                                    comment 
   2774.8586747  1064.28754926  point           inf           inf               0.0  99997                                                    comment 
  2967.73158838  1064.22317816  point           inf           inf               0.0  99998                                                    comment 
  1501.88247139   1064.3341842  point           inf           inf               0.0  99999                                                    comment 
  2819.86244032  1064.27387814  point           inf           inf               0.0 100000                                                    comment 
  1045.41197864  1064.19089426  point           inf           inf               0.0 100001                                                    comment

**Comment by meredith-durbin** [comment]
@benw1 Is this something inbuilt into STIPS that fails when reading in the table? If not, the following works for me:

```
In [1]: from astropy.table import Table
In [2]: Table.read('stips_output.txt', format='ascii', delimiter=' ')
Out[2]: 
<Table length=16>
     col1          col2      col3   col4    col5    col6    col7     col8 
   float64       float64     str5 float64 float64 float64 float64    str7 
------------- ------------- ----- ------- ------- ------- -------- -------
 2517.6913324 1064.34991998 point     inf     inf     0.0  99986.0 comment
1804.05356529  1064.3825735 point     inf     inf     0.0  99987.0 comment
2376.24982102 1064.37279608 point     inf     inf     0.0  99988.0 comment
1720.47366272 1064.37289225 point     inf     inf     0.0  99989.0 comment
3064.16935295   1064.185337 point     inf     inf     0.0  99990.0 comment
2254.09638279 1064.38602616 point     inf     inf     0.0  99991.0 comment
1489.02462552 1064.33130414 point     inf     inf     0.0  99992.0 comment
1579.03215135 1064.35005763 point     inf     inf     0.0  99993.0 comment
1315.43718858 1064.28586191 point     inf     inf     0.0  99994.0 comment
1746.19195883 1064.37617288 point     inf     inf     0.0  99995.0 comment
1437.59063619 1064.31911307 point     inf     inf     0.0  99996.0 comment
 2774.8586747 1064.28754926 point     inf     inf     0.0  99997.0 comment
2967.73158838 1064.22317816 point     inf     inf     0.0  99998.0 comment
1501.88247139  1064.3341842 point     inf     inf     0.0  99999.0 comment
2819.86244032 1064.27387814 point     inf     inf     0.0 100000.0 comment
1045.41197864 1064.19089426 point     inf     inf     0.0 100001.0 comment
```

(I'd also point out that the mixing of float and integer values in the second to last column could potentially be a concern.)

**Comment by benw1** [comment]
Sorry, I should have included the header. Because the header has |
dividers, astropy seems to use the those widths, which generates an error
when it gets to the wider line.

**Comment by benw1** [comment]
Header is this:

|            x|            y| type|      vegamag|        stmag|   countrate|     id|  notes|
|       double|       double| char|       double|       double|      double| double|   char|
|       pixels|       pixels|     |             |             |    counts/s|       |       |
|         null|         null| null|         null|         null|        null|   null|   null|

**Comment by benw1** [comment]
By the way, the editor is changing the spacing in the example above, to see the true column spacing (and the abrupt change) you need to click the edit button on the comment.

**Comment by york-stsci** [comment]
This is the result of a number of things interacting, and it suggests to me that I might want to overhaul the table interface in the near future, possibly in a non-backwards-compatible way. Currently, what I'm looking for in a table format is:
- ASCII (I want it to be possible to easily open a table and look for a particular value)
- Metadata in the table (since I want to be able to store/retrieve table metadata without needing a separate file)
- The ability to read/write a table iteratively inside a loop (because STIPS can generate, or receive, tables with millions of lines, and I don't want to have all of that hanging around in memory at the same time)
IPAC mostly has all of this. The biggest problem is that, if the table is long enough to be written as multiple segments, astropy sets the column formatting for each segment separately (and as far as I can tell there isn't any way to override the formatting). I still don't have a good solution for this. Nor does astropy (as far as I can see) let you write the table data without a header, so I have a set of hacks in place for not repeating header data.
ECSV looks as if it might be as good as IPAC, but it would be a bit difficult to make things backwards-compatible.

**Comment by benw1** [comment]
As a temporary solution, perhaps you could add a copy of the table in fits or hdf5.  There are ways to open those and look through in jupyter or other applications.  You could still also include the ascii output for those who need it.

**Comment by benw1** [comment]
Is this additional output list format a possibility?  We are finding the current multi-width format is blocking our ability to process the output ascii lists.

**Comment by york-stsci** [comment]
The updated version of master now has the option to produce output fits in FITS format. In addition, the default output format has been changed to FITS.
