### ISSUE TITLE
Add Example Catalog and Script

### ISSUE THREAD

**Issue by benw1** [spacetelescope/STScI-STIPS#24]
I am putting together a STIPS for WFIRST cookbook for AAS.  I'd like to accompany it with an example script (example.py) and catalog (input_sources.txt) that can be used as a test of a STIPS installation.  I attach a pdf version of the  current document draft for you to inspect.  
[cookbook.pdf](https://github.com/spacetelescope/STScI-STIPS/files/2621686/cookbook.pdf)

**Comment by york-stsci** [comment]
This has now been done.
