### ISSUE TITLE
Add spatial variation of PSF

### ISSUE THREAD

**Issue by benw1** [spacetelescope/STScI-STIPS#27]
Need to add/test effects of spatially-varying PSF

**Comment by benw1** [comment]
The reference data for doing this enhancement is now available in Webbpsf 0.9.  What kind of support do we need in order to implement it in STIPS?  If speed is a problem, we could try generating 4 PSFs for each detector in order to cover the quadrants, and doing this separately for each of the 18 detectors given their positions on the focal plane.  This way the STIPS would only be a look-up table of 4 (16? 64?) PSFs generated for the simulation instead of a single one.  That hopefully would not slow things down too terribly.

**Comment by benw1** [comment]
The reference data for doing this enhancement is now available in Webbpsf 0.9.  What kind of support do we need in order to implement it in STIPS?  If speed is a problem, we could try generating 4 PSFs for each detector in order to cover the quadrants, and doing this separately for each of the 18 detectors given their positions on the focal plane.  This way the STIPS would only be a look-up table of 4 (16? 64?) PSFs generated for the simulation instead of a single one.  That hopefully would not slow things down too terribly.

**Comment by benw1** [comment]
Any thoughts or plans for adding this capability would be greatly appreciated.  Thanks.

**Comment by benw1** [comment]
One way to achieve this perhaps more easily would be to use a pre-computed grid of PSFs.  Jeff Kruk has these and is happy to help with this effort.

**Comment by york-stsci** [comment]
I'm currently testing this issue. Hopefully we will have a PR that handles it at some point this week.
