### ISSUE TITLE
Specifying galaxy brightnesses

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/STScI-STIPS#30]
I was a bit surprised that the STIPS web interface asked me to specify galaxy brightnesses in units that don't seem very intuitive: "Apparent Average Surface Brightness Lower Bound (Johnson, V)." A few comments on this...

- Personally I would find it more convenient to specify the bounds of the total AB magnitudes in the selected band that I'm simulating (or at least in some infrared band. V band is too far away to be particularly intuitive, and most of the extragalactic community is using AB magnitudes these days). 

- Surface brightness is not so intuitive. When specifying it, I think most extragalactic astronomers would use the central surface brightness or the surface-brightness at the half-light radius, rather than the average surface brightness (which is actually undefined for some values of n in the Sersic profile).

- The documentation is inconsistent with the web form. It shows a form asking for the "Apparent VMAG Lower Bound" rather than surface brightness. But then below that screenshot of the form it mentions surface brightness.

**Comment by robelgeda** [comment]
This issue has been addressed by v1.0.7.
