### ISSUE TITLE
Rebooting Server

### ISSUE THREAD

**Issue by robelgeda** [spacetelescope/STScI-STIPS#34]
Check if the Docker are auto restarting when the machine is restarted.

**Comment by york-stsci** [comment]
This is really more an issue with the webserver than with the STIPS module. I would suggest opening this as a new issue on STSCI-STIPS-UI and then closing it here.

**Comment by robelgeda** [comment]
Issue has been transferred 
https://github.com/spacetelescope/STScI-STIPS-UI/issues/7
