### ISSUE TITLE
Need output PSF in consistent format

### ISSUE THREAD

**Issue by benw1** [spacetelescope/STScI-STIPS#43]
We would like to be able to use the output PSF images in each band for PSF photometry fitting, but to do that, we need to know the scaling of those images.  For example, if I run simualtions in 6-bands (R,Z,Y,J,H,F184), all with 10x oversampling I get nearly 6 different PSF image sizes

sim_13003_0_psf.fits: 910x910 float, 1.0s
sim_13005_0_psf.fits: 1190x1190 float, 1.0s
sim_13007_0_psf.fits: 1440x1440 float, 1.0s
sim_13009_0_psf.fits: 1760x1760 float, 1.0s
sim_13011_0_psf.fits: 2040x2040 float, 1.0s
sim_13013_0_psf.fits: 2040x2040 float, 1.0s

and I don't know what the pixel scale is for any of them, because the header is set to 1 arcsec/pixel

PC1_1   =  0.00027777777777778 / Coordinate transformation matrix element       
PC2_2   =  0.00027777777777778 / Coordinate transformation matrix element       
CDELT1  = 0.000277777777777777 / [deg] Coordinate increment at reference point  
CDELT2  = 0.000277777777777777 / [deg] Coordinate increment at reference point  

Ideally, these would all be the same size, and the pixel scale in the header should be corrected.

**Comment by benw1** [comment]
This PSF issue is my largest block at the moment, so I'd very much appreciate any help, and I'm willing to help with it if someone points me at a good place to start.

**Comment by robelgeda** [comment]
I can help with this and will try to fit it into the current milestone
