### ISSUE TITLE
Zeropoints for WFIRST bands

### ISSUE THREAD

**Issue by benw1** [spacetelescope/STScI-STIPS#75]
Looking at the catalogs produced by STIPS that provide the count rate, and the magnitudes, we are seeing that all of the filters except F184 are using the same zeropoint (28.124).  Do we have documentation of what the zero points should be, and is that value correct to be used for all bands other than F184?

**Comment by york-stsci** [comment]
So, we don't have any documentation, and thus I'm currently using the WFC3IR method for figuring out zero point. In particular, what I do is:

- Open the STScI standard spectrum of Vega
- Create the current WFIRST filter bandpass
- Renormalize Vega to have a magnitude of 0.0 VEGAMAG in the WFIRST filter bandpass.
- Observe the spectrum in pysynphot
- Set the zeropoint to the OBMAG magnitude of the observation.

If there's another way that I should be doing this, let me know.

**Comment by benw1** [comment]
That sounds like it should be correct, but it also sounds like it should result in a different zero point in F158 and F087.  According to my STIPS catalogs that are returned by the code, the zero point of these filters is precisely identical (see attached screed shot showing the identical count rates for the two bands with the same input magnitude).  I'm wondering if there's a problem with this part of the code that could cause the zero points to always be the same, no matter what the band.
<img width="1400" alt="Screen Shot 2020-05-20 at 11 50 00 AM" src="https://user-images.githubusercontent.com/8866546/82485625-9260b180-9a90-11ea-9f1a-b6e78ff6ec19.png">

**Comment by york-stsci** [comment]
Except that I have a bug. In particular, because generating the bandpass takes awhile, I cache the value, and I didn't delete the cached value when changing filters. On the plus side, this should be an easy fix.
