### ISSUE TITLE
Multiple filters showing same zeropoint

### ISSUE THREAD

**Issue by benw1** [spacetelescope/STScI-STIPS#83]
When running version 1.0.8, I get the same zero point for multiple filters.  These identical zero points suggest that there is some kind of issue with how they are being calculated or applied.  See the two tables in the image attached, which show that for F158 and F062 the magnitude assigned for the count rate is identical.
<img width="1404" alt="Screen Shot 2020-05-21 at 5 06 29 PM" src="https://user-images.githubusercontent.com/8866546/82617866-37a98180-9b86-11ea-9c6e-3748152decf0.png">

**Comment by york-stsci** [comment]
Looking at this, I ran a fairly simple script. Starting with the get_default_obs() function in the stips/tests/test_wfirst.py to create an observation dictionary, I then did:

`observation = get_default_obs()`
`filters = stips.instruments.wfi.WFI.filters`
`for filter in filters:`
`    observation['filters'] = [filter]`
`    obm = ObservationModule(observation)`
`    obm.nextObservation()`
`    print(filter, obm.instrument.zeropoint)`

The results I got were as follows:
F062 -26.470912243475663
F087 -25.991214325130887
F106 -25.85848585832499
F129 -25.519656868290813
F158 -25.21869007796093
F184 -24.587525340768124
F146 -26.73683813344697

So at least to me it looks a lot as if there are in fact different zero points for different filters. I can't really speak to the screenshots, because I don't have enough data on how they were generated.

**Comment by benw1** [comment]
These are the output fits tables that are generated by STIPS that describe the sources STIPS put into the image. In both filter examples, a count rate of 16.42 corresponds to a vegamag of 25.07. This would suggest a zeropoint of -28.12 which doesn't match anything in your list. Perhaps the issue is in the fits catalog generation?

**Comment by york-stsci** [comment]
The lines that generate the magnitudes are:

`vegamags = -2.512 * np.log10(fluxes) - self.zeropoint`
`stmags = -2.5 * np.log10(fluxes * self.photflam) - 21.10`

This code (and, indeed, the code that covers table creation) is exactly the same between 1.0.7 and 1.0.8, so could you provide an example of running the same test on 1.0.7 (and with the 1.0.7 data instead of the 1.0.8 data) so that I can see what this looked like previously?

**Comment by benw1** [comment]
I'd be happy to try this.  I have not done any data updates.  I have only done "git pull" and "python setup.py install".  Is there a simple way using git to revert to 1.0.7?

**Comment by york-stsci** [comment]
The easiest way to revert to 1.0.7 is to go to <https://github.com/spacetelescope/STScI-STIPS/releases>, click on "Assets" under 1.0.7, and take your pick of the source code.

Under 1.0.8 (as I think we put in the release notes?) the STIPS data files are now maintained on Box instead of as part of this repository. The STIPS 1.0.8 data can be downloaded at <https://stsci.box.com/shared/static/d4repaci5st9mp0qstlynt67q6qwpig0.gz>. I don't know offhand which changes exactly were made as part of the 1.0.7 to 1.0.8 move, but I would strongly recommend that you use that data with 1.0.8.

**Comment by benw1** [comment]
OK, I'll try this.  Then when I switch back to 1.0.8, I'll update the data as well.
Here are my scripts for the 2 runs:
F062:
seed = np.random.randint(9999)+1000
scene_general = {'ra': 25.65,'dec': -37.21,'pa': 0.0, 'seed': seed}
obs = {'instrument': 'WFI', 'filters': ['F062'], 'detectors': 1,'distortion': False, 'oversample': 1,'pupil_mask': '', 'background': 'avg','observations_id': 70, 'exptime': 10
000.0,'offsets': [{'offset_id': 3, 'offset_centre': False,'offset_ra': 0.0, 'offset_dec': 0.0, 'offset_pa': 0.0}]}
obm = ObservationModule(obs, scene_general=scene_general)
obm.nextObservation()
source_count_catalogues = obm.addCatalogue(str(filename))
psf_file = obm.addError()
fits_file, mosaic_file, params = obm.finalize(mosaic=False)

F158:

seed = np.random.randint(9999)+1000
scene_general = {'ra': 25.65,'dec': -37.21,'pa': 0.0, 'seed': seed}
obs = {'instrument': 'WFI', 'filters': ['F158'], 'detectors': 1,'distortion': False, 'oversample': 1,'pupil_mask': '', 'background': 'avg','observations_id': 74, 'exptime': 10
000.0,'offsets': [{'offset_id': 3, 'offset_centre': False,'offset_ra': 0.0, 'offset_dec': 0.0, 'offset_pa': 0.0}]}
obm = ObservationModule(obs, scene_general=scene_general)
obm.nextObservation()
source_count_catalogues = obm.addCatalogue(str(filename))
psf_file = obm.addError()
fits_file, mosaic_file, params = obm.finalize(mosaic=False)

**Comment by york-stsci** [comment]
Thank you. Can you also provide the file(s) you're using?

**Comment by benw1** [comment]
Here are the first few lines of the input catalog files (the whole file is not accepted by GitHub).  Is there another file you would like?

MacBook-Pro-9:Downloads ben$ head example_F062.cat 
\type = internal
\filter = F062
\center = (25.65  -37.21)
|        id|             ra|            dec|           flux|    type|         n|             re|            phi|          ratio|   notes|
|    double|         double|         double|         double|    char|    double|         double|         double|         double|    char|
|          |               |               |               |        |          |               |               |               |        |
|      null|           null|           null|           null|    null|      null|           null|           null|           null|    null|
         60      25.6136666     -37.2215226      16.4285790    point      1.000       1.0000000       1.0000000       1.0000000  comment 
         69      25.5754022     -37.2215226      15.0244990    point      1.000       1.0000000       1.0000000       1.0000000  comment 
        110      25.7001344     -37.2215226       0.5638973    point      1.000       1.0000000       1.0000000       1.0000000  comment 
MacBook-Pro-9:Downloads ben$ head example_F158.cat 
\type = internal
\filter = F158
\center = (25.65  -37.21)
|        id|             ra|            dec|           flux|    type|         n|             re|            phi|          ratio|   notes|
|    double|         double|         double|         double|    char|    double|         double|         double|         double|    char|
|          |               |               |               |        |          |               |               |               |        |
|      null|           null|           null|           null|    null|      null|           null|           null|           null|    null|
         60      25.6136666     -37.2215226      16.4285790    point      1.000       1.0000000       1.0000000       1.0000000  comment 
         69      25.5754022     -37.2215226      15.0244990    point      1.000       1.0000000       1.0000000       1.0000000  comment 
        110      25.7001344     -37.2215226       0.5638973    point      1.000       1.0000000       1.0000000       1.0000000  comment 
MacBook-Pro-9:Downloads ben$

**Comment by benw1** [comment]
I receive the following warnings, in case they are relevant:
WARNING: UnitsWarning: 'counts/s' did not parse as fits unit: At col 0, Unit 'counts' not supported by the FITS standard. Did you mean count? [astropy.units.core]
WARNING: VerifyWarning: Keyword name 'input_catalogue' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created. [astropy.io.fits.card]

**Comment by benw1** [comment]
The output fits table is identical to the one I posted using 1.0.8.  Would you like me to post the screen shot?

**Comment by benw1** [comment]
I'm trying to reproduce your zeropoint check, but can't seem to get the first line to work, even in 1.0.8:

>>> import stips
>>> print(stips.__version__)
dev
>>> observation = get_default_obs()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'get_default_obs' is not defined
>>> filters = stips.instruments.wfi.WFI.filters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'WFI' has no attribute 'filters'
>>>

**Comment by york-stsci** [comment]
Thank you. So it looks like this is not specific to 1.0.8, but goes back at least as far as 1.0.7. As such, I'm going to investigate it, and I'll do my best to fix it in 1.0.9, but I'm not considering it a regression with this release.

As for not being able to get the text to work, I was using a bit of a shorthand (I was assuming that you'd go to the stips/tests/test_wfirst.py file, and copy-and-paste the get_default_obs() function defined in that file into your python session directly before calling it).

**Comment by benw1** [comment]
I could not get the loop to work, as I get:
>>> filters = stips.instruments.wfi.WFI.filters
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'WFI' has no attribute 'filters'
>>> 

However, just using the default filter, I get the zero point that is consistent with the screenshots I sent you, namely:

>>> print(observation['filters'], obm.instrument.zeropoint)
['F129'] -28.130926290748853
>>> 

So something is different between our versions, but I'm not sure what or how.

**Comment by benw1** [comment]
Could this be related to the fact that I'm set up to run offline by having put local versions of the Sky Background Database Files in .../site-packages/jwst_backgrounds/refdata?  That is at least something different between our environments...

**Comment by benw1** [comment]
I've done another installation on a different machine.  I still get the same wrong zeropoint:
>>> obs = get_default_obs()
>>> obm = ObservationModule(obs)
>>> obm.nextObservation()
2020-05-29 15:32:02,831 INFO: Initializing Observation 0 of 1
2020-05-29 15:32:02,831 INFO: Observation Filter is F158
2020-05-29 15:32:02,831 INFO: Observation (RA,DEC) = (0.000139,0.000000) with PA=27.000000
2020-05-29 15:32:02,832 INFO: Resetting
2020-05-29 15:32:05,835 INFO: Using local cache of JBT background data
2020-05-29 15:32:05,884 INFO: Creating Instrument with Configuration {'aperture': 'any', 'disperser': None, 'filter': 'f158', 'instrument': 'wfirstimager', 'mode': 'imaging'}
2020-05-29 15:32:06,008 INFO: Returning background 9.85775400939481 for 'avg'
2020-05-29 15:32:06,008 INFO: Creating Detector SCA01 with (RA,DEC,PA) = (0.0001388888888888889,0.0,27.0)
2020-05-29 15:32:06,008 INFO: Creating Detector SCA01 with offset (0.0,0.0)
/nobackup/bwilli24/miniconda3/envs/STIPS/lib/python3.6/site-packages/pysynphot/units.py:851: RuntimeWarning: divide by zero encountered in log
  return -1.085736 * N.log(arg) + STZERO
2020-05-29 15:32:08,751 INFO: PSF choosing between 4096, 4096 and 215
2020-05-29 15:32:08,751 INFO: SCA01: Starting 1x1 PSF Grid creation at Fri May 29 15:32:08 2020

Running instrument: WFI, filter: F158
  Running detector: SCA01
    Position 1/1: (2047, 2047) pixels
2020-05-29 15:32:39,389 INFO: SCA01: Finished PSF Grid creation at Fri May 29 15:32:39 2020
2020-05-29 15:32:39,844 INFO: SCA01: (RA, DEC, PA) := (0.0001388888888888889, 0.0, 27.0), detected as (0.0001388888888888889, 0.0, 27.000000000000913)
2020-05-29 15:32:39,844 INFO: Detector SCA01 created
2020-05-29 15:32:39,844 INFO: Reset Instrument
0
>>> print(obs['filters'], obm.instrument.zeropoint)
['F158'] -28.130926290748853
>>>

**Comment by benw1** [comment]
I was able to install the docker version on my laptop, and that version reproduces the proper zero points.  
>>> print(observation['filters'], obm.instrument.zeropoint)
['F158'] -25.21869007796093
>>> 
Now I can look into how my hand-installed version differs because I do not have access to docker on the supercomputer, and my hand-installed version is not getting the zero points correct.

**Comment by benw1** [comment]
It looks like if it start from scratch, creating a brand new conda environment and deleting all of by STScI-STIPS and STScI-STIPS-UI directories from old builds, the zero points come out correctly.  There must be something about an older version that does not get replaced with a git pull that is responsible for the zero point issue.  I still need to install the local background files in this new installation, and I will check the zero points again after doing that.

**Comment by york-stsci** [comment]
I've added issue #87 which should make it easier to do this sort of comparison. Meanwhile, are you still having the zero point issue (that you originally reported here) with your new version (i.e. are the zero point and magnitude values still incorrect)?

**Comment by benw1** [comment]
Generating a new environment, I can confirm results in the zero points that Brian gets.  I do not know if they are correct, but they are different for the different bands, matching Brian's values.
