### ISSUE TITLE
Docker build fails to get synphot files

### ISSUE THREAD

**Issue by benw1** [spacetelescope/STScI-STIPS#86]
When installing the latest version with docker, I'm getting the following error:
(STIPS) bash-3.2$ docker build -t stips .

...

Step 25/54 : RUN wget -qO- http://ssb.stsci.edu/cdbs/tarfiles/synphot1.tar.gz | tar xvz
 ---> Running in 57a265ccc155

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c wget -qO- http://ssb.stsci.edu/cdbs/tarfiles/synphot1.tar.gz | tar xvz' returned a non-zero code: 2
(STIPS) bash-3.2$ 

I can retrieve and untarnished the file by hand, but it fails in docker.  Perhaps the docker command needs additional flags?

**Comment by benw1** [comment]
Looks like the wget commands need a --no-check-certificate in them in order to succeed when getting files from ssb.stsci.edu

**Comment by york-stsci** [comment]
I think this was a result of a certificate expiration issue that STScI had specifically at the time when you were trying to retrieve the files. Can you try again without the no_check flag and let me know what happens please?

**Comment by york-stsci** [comment]
Closing this issue as I haven't heard that it's still a problem with the renewed certificate.
