### ISSUE TITLE
PSF library would speed up image creation

### ISSUE THREAD

**Issue by benw1** [spacetelescope/STScI-STIPS#89]
The PSF grid takes a long time to calculate. It would be nice to only do this once for each filter/detector.  The code could store the results in the stips_data tree for future runs.  Even better, a starter grid for the PSFs of SCA01 could ship with the STIPS data, greatly improving the run times.

**Comment by benw1** [comment]
Also, it looks like the file output to psf_cache/ only has a single PSF, not the entire grid of PSFs.  Is there a way to generate the library of spatially-varying PSFs that STIPS used to create the image?

**Comment by york-stsci** [comment]
The output to psf_cache in version 1.0.8 is a single GriddedPSFModel, so it already contains a grid of whatever size was specified. If something else is produced, please open an issue specifically for that.

Meanwhile, this is something that has already been implemented, in that if the psi_cache directory is supplied, it will automatically be populated by PSF grids as they are generated (and grids will be re-used if applicable), and it is entirely possible to use webbpsf to create GriddedPSFModel files and store them in the psf_cache location before running STIPS at all, in which case STIPS will automatically use those PSFs.

As such, I'm closing this issue.

**Comment by benw1** [comment]
When run STIPS, and the psf_cache already exists, it regenerates the PSFs even if they are already there:
For example, before running I get:

ls -alstr /nobackup/bwilli24/psf_cache/*F106*
331112 -rw-r----- 1 bwilli24 s1692  339048000 Sep 19 19:12 /nobackup/bwilli24/psf_cache/psf_WFI_1.0.8_F106_3_5_sca01.fits

then after running:

ls -alstr /nobackup/bwilli24/psf_cache/*F106*
 331112 -rw-r----- 1 bwilli24 s1692  339048000 Sep 21 11:16 /nobackup/bwilli24/psf_cache/psf_WFI_1.0.8_F106_3_5_sca01.fits
 
I would very much like it to use the library instead of recalculating every time.  How can I do that?
