### ISSUE TITLE
psf_grid_size keyword is not passed on from ObservationModule to Instrument

### ISSUE THREAD

**Issue by york-stsci** [spacetelescope/STScI-STIPS#92]
The ObservationModule code does not check its keyword arguments for the new psf_grid_size keyword. This is ported over from documentation issue #81

**Comment by york-stsci** [comment]
I have made a release on my fork of STIPS that has a fix of this issue. *NOTE* that the psf_grid_size keyword is supplied directly to the ObservationModule, and is *not* part of the observation (`obs`) dictionary.

The fix release is at https://github.com/york-stsci/STScI-STIPS-1/releases/tag/v1.0.8-fix1

**Comment by benw1** [comment]
Thanks!
I updated the files in my STScI-STIPS/ directory with these updates, and now stips is hanging on install at MANIFEST.in
l:
(stips) -bash-4.3$ python setup.py install
git submodule command failed unexpectedly:
error: pathspec 'astropy_helpers' did not match any file(s) known to git
Downloading 'astropy-helpers'; run setup.py with the --offline option to force offline installation.
running install
running bdist_egg
running egg_info
writing stips.egg-info/PKG-INFO
writing dependency_links to stips.egg-info/dependency_links.txt
writing entry points to stips.egg-info/entry_points.txt
writing requirements to stips.egg-info/requires.txt
writing top-level names to stips.egg-info/top_level.txt
reading manifest file 'stips.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'

**Comment by york-stsci** [comment]
There's now a new fix release at https://github.com/york-stsci/STScI-STIPS-1/releases/tag/v1.0.8-fix2

**Comment by benw1** [comment]
This fix worked for me! Thanks!
