### ISSUE TITLE
Add Readnoise to the header

### ISSUE THREAD

**Issue by benw1** [spacetelescope/STScI-STIPS#97]
While the readnoise is mentioned in the history, it should have a dedicated header keyword like a real observed image would.

**Comment by york-stsci** [comment]
Just checking that the keyword in question is "READNOIS" (which is what I think I remember it usually being)?

**Comment by benw1** [comment]
I'm used to seeing RDNOISE, but the main thing is to have a separate keyword for it that is not a HISTORY key. If you want to use READNOIS that would be fine too. Thanks!
